/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export type UserBridgeDataStruct = {
  nextPaymentTime: PromiseOrValue<BigNumberish>;
  subscriptionDuration: PromiseOrValue<BigNumberish>;
  subscriptionLimit: PromiseOrValue<BigNumberish>;
};

export type UserBridgeDataStructOutput = [BigNumber, BigNumber, BigNumber] & {
  nextPaymentTime: BigNumber;
  subscriptionDuration: BigNumber;
  subscriptionLimit: BigNumber;
};

export interface BridgeFacetInterface extends utils.Interface {
  functions: {
    "changeSubscriptionLimit(uint256,uint256,uint256)": FunctionFragment;
    "users(uint256,uint256,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "changeSubscriptionLimit" | "users"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "changeSubscriptionLimit",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "users",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeSubscriptionLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;

  events: {
    "EditSubscriptionLimit(address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "EditSubscriptionLimit"): EventFragment;
}

export interface EditSubscriptionLimitEventObject {
  user: string;
  chainId: BigNumber;
  subscriptionManagerId: BigNumber;
  amountMaxPerPeriod: BigNumber;
}
export type EditSubscriptionLimitEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  EditSubscriptionLimitEventObject
>;

export type EditSubscriptionLimitEventFilter =
  TypedEventFilter<EditSubscriptionLimitEvent>;

export interface BridgeFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BridgeFacetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    changeSubscriptionLimit(
      chainId: PromiseOrValue<BigNumberish>,
      subscriptionManagerId: PromiseOrValue<BigNumberish>,
      amountMaxPerPeriod: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    users(
      srcChainId: PromiseOrValue<BigNumberish>,
      subManagerId: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[UserBridgeDataStructOutput]>;
  };

  changeSubscriptionLimit(
    chainId: PromiseOrValue<BigNumberish>,
    subscriptionManagerId: PromiseOrValue<BigNumberish>,
    amountMaxPerPeriod: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  users(
    srcChainId: PromiseOrValue<BigNumberish>,
    subManagerId: PromiseOrValue<BigNumberish>,
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<UserBridgeDataStructOutput>;

  callStatic: {
    changeSubscriptionLimit(
      chainId: PromiseOrValue<BigNumberish>,
      subscriptionManagerId: PromiseOrValue<BigNumberish>,
      amountMaxPerPeriod: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    users(
      srcChainId: PromiseOrValue<BigNumberish>,
      subManagerId: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<UserBridgeDataStructOutput>;
  };

  filters: {
    "EditSubscriptionLimit(address,uint256,uint256,uint256)"(
      user?: PromiseOrValue<string> | null,
      chainId?: PromiseOrValue<BigNumberish> | null,
      subscriptionManagerId?: PromiseOrValue<BigNumberish> | null,
      amountMaxPerPeriod?: null
    ): EditSubscriptionLimitEventFilter;
    EditSubscriptionLimit(
      user?: PromiseOrValue<string> | null,
      chainId?: PromiseOrValue<BigNumberish> | null,
      subscriptionManagerId?: PromiseOrValue<BigNumberish> | null,
      amountMaxPerPeriod?: null
    ): EditSubscriptionLimitEventFilter;
  };

  estimateGas: {
    changeSubscriptionLimit(
      chainId: PromiseOrValue<BigNumberish>,
      subscriptionManagerId: PromiseOrValue<BigNumberish>,
      amountMaxPerPeriod: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    users(
      srcChainId: PromiseOrValue<BigNumberish>,
      subManagerId: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    changeSubscriptionLimit(
      chainId: PromiseOrValue<BigNumberish>,
      subscriptionManagerId: PromiseOrValue<BigNumberish>,
      amountMaxPerPeriod: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    users(
      srcChainId: PromiseOrValue<BigNumberish>,
      subManagerId: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
