/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iOpenOceanSol from "./IOpenOcean.sol";
export type { iOpenOceanSol };
export type { IERC20 } from "./IERC20";
export type { ILiFi } from "./ILiFi";
