/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LibAdmin__factory } from "./LibAdmin__factory";
export { LibDiamond__factory } from "./LibDiamond__factory";
